source: /Users/GopolangM/Library/CloudStorage/GoogleDrive-gopolangmakokwe@gmail.com/My Drive/0. Writing Projects/1. Books/Study Guides/Solidity with AI/SolidCobra
destination: _site
cache_dir: .jekyll-cache 
